spring:
  datasource:
    url: jdbc:mysql://todo-mysql:3306/todo_db?useSSL=false&serverTimezone=UTC
    username: ${SPRING_DATASOURCE_USERNAME:springstudent}
    password: ${SPRING_DATASOURCE_PASSWORD:springstudent}

  redis:
    host: ${SPRING_REDIS_HOST:todo-redis}  # if running in Docker, use service name
    port: ${SPRING_REDIS_PORT:6379}
