spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/todo_db}
    username: ${SPRING_DATASOURCE_USERNAME:springstudent}
    password: ${SPRING_DATASOURCE_PASSWORD:springstudent}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
